import { NextResponse } from "next/server";
import { getAdminClient } from "@/lib/supabase/admin";
import { PRODUCTS } from "@/data/products";
import type { OrderItemSnapshot, PaymentMethod } from "@/types";

interface CheckoutRequest {
  customer: {
    name: string;
    email: string;
    phone: string;
  };
  shippingAddress: {
    street: string;
    number: string;
    apartment?: string;
    city: string;
    province: string;
    zip: string;
    notes?: string;
  };
  items: OrderItemSnapshot[];
  subtotal: number;
  shippingCost: number;
  total: number;
  paymentMethod: PaymentMethod;
  notes?: string;
}

function generateLocalCode(): string {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const suffix = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `KLT-${date}-${suffix}`;
}

export async function POST(request: Request) {
  let body: CheckoutRequest;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Body inválido" },
      { status: 400 },
    );
  }

  // Basic validation
  if (
    !body.customer?.email ||
    !body.customer?.name ||
    !body.customer?.phone ||
    !body.shippingAddress?.city ||
    !body.shippingAddress?.province ||
    !body.items?.length ||
    body.total <= 0
  ) {
    return NextResponse.json(
      { error: "Faltan datos obligatorios" },
      { status: 400 },
    );
  }

  // Try to use Supabase if configured
  const admin = getAdminClient();

  if (admin) {
    try {
      // Insert order — code is auto-generated by trigger
      const { data: order, error: orderError } = await admin
        .from("orders")
        .insert({
          customer: body.customer,
          shipping_address: body.shippingAddress,
          items: body.items,
          subtotal: body.subtotal,
          shipping_cost: body.shippingCost,
          total: body.total,
          payment_method: body.paymentMethod,
          status: "pending",
          notes: body.notes ?? null,
        })
        .select("id, code")
        .single();

      if (orderError || !order) {
        console.error("[checkout] order insert error", orderError);
        throw new Error(orderError?.message ?? "DB error");
      }

      // Insert order_items rows for analytics
      const itemRows = body.items.map((i) => ({
        order_id: order.id,
        product_id: PRODUCTS.some((p) => p.id === i.productId)
          ? null // local seed id, not a real UUID
          : i.productId,
        product_name: i.productName,
        product_slug: i.productSlug,
        unit_price: i.unitPrice,
        quantity: i.quantity,
      }));

      const { error: itemsError } = await admin
        .from("order_items")
        .insert(itemRows);

      if (itemsError) {
        console.warn("[checkout] order_items insert warning", itemsError);
        // Don't fail the order if analytics rows fail
      }

      return NextResponse.json({
        ok: true,
        code: order.code,
        id: order.id,
      });
    } catch (err) {
      console.error("[checkout] supabase error", err);
      return NextResponse.json(
        {
          error:
            "No pudimos guardar tu pedido en este momento. Probá de nuevo o escribinos por WhatsApp.",
        },
        { status: 500 },
      );
    }
  }

  // Fallback when Supabase is not configured: log and return a synthetic code.
  // Useful for local dev without DB.
  const code = generateLocalCode();
  console.log("[checkout] order received (no DB)", {
    code,
    customer: body.customer.email,
    total: body.total,
  });

  return NextResponse.json({
    ok: true,
    code,
    id: code,
    fallback: true,
  });
}
